[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gridflow-analytics"
version = "0.1.0"
description = "Electricity Analytics Platform built using Azure, Databricks and Spark."
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Srijan" }
]

dependencies = [
    "pyspark>=3.5.0",
    "delta-spark",
    "python-dotenv",
    "requests"
]

[project.scripts]
demand-ingestion = "gridflow_analytics.ingestion.demand_ingestion:main"
national-demand-ingestion = "gridflow_analytics.ingestion.national_demand_ingestion:main"
national-fuelmix-ingestion = "gridflow_analytics.ingestion.national_fuelmix_ingestion:main"
frequency-ingestion = "gridflow_analytics.ingestion.frequency_ingestion:main"
weather-ingestion = "gridflow_analytics.ingestion.weather_ingestion:main"
psp-ingestion = "gridflow_analytics.ingestion.psp_ingestion:main"

demand-silver = "gridflow_analytics.processing.demand_silver:main"
national-demand-silver = "gridflow_analytics.processing.national_demand_silver:main"
national-fuelmix-silver = "gridflow_analytics.processing.national_fuelmix_silver:main"
frequency-silver = "gridflow_analytics.processing.frequency_silver:main"
weather-silver = "gridflow_analytics.processing.weather_silver:main"
psp-silver = "gridflow_analytics.processing.psp_silver:main"

state-demand-gold = "gridflow_analytics.processing.state_demand_gold:main"
national-grid-gold = "gridflow_analytics.processing.national_grid_gold:main"
state-adequacy-gold = "gridflow_analytics.processing.state_adequacy_gold:main"
state-weather-demand-gold = "gridflow_analytics.processing.state_weather_demand_gold:main"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["gridflow_analytics*"]